apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sdk-app
  labels:
    app: java-sdk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sdk-app
  template:
    metadata:
      labels:
        app: java-sdk-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "java-sdk-app"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: java
        image: dapr-pub-sub-examples-java-sdk:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1.0"