apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "php-app"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: php
        image: dapr-pub-sub-examples-php-sdk:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: "1.0"
        env:
        - name: APP_KEY
          value: "base64:d6KIQuhFaeLlLeBtuiC9Q8Z9HvO2w4QmLI2Gp3KbHkM="