apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://some-event-hub.servicebus.windows.net/;SharedAccessKeyName=root;SharedAccessKey=Ex7eWK2aDOW63iEWzNYaxIzU+8hpgPUUE+AEhPmpIms=;EntityPath=orders"
  - name: storageAccountName
    value: "somestorageaccount"
  - name: storageAccountKey
    value: "[connection_string]"
  - name: storageContainerName
    value: "orders"
  - name: consumerID
    value: "checkpoint"
scopes:
  - node-app