apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "go-app"
        dapr.io/app-port: "3000"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: go
        image: dapr-pub-sub-examples-go-http:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1.0"