apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dotnet-app"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: dotnet
        image: dapr-pub-sub-examples-dotnet-http:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1.0"