apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31110
  type: NodePort