apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://someeh.servicebus.windows.net/;SharedAccessKeyName=root;SharedAccessKey=xxxxxxxx;EntityPath=orders"
  - name: storageAccountName
    value: "somestorage"
  - name: storageAccountKey
    value: "xxxxxxxxxx"
  - name: storageContainerName
    value: "orders"
  - name: consumerID
    value: "$default"
scopes:
  - go-app